# Implementation of Naive Bayes classifier

* Dataset: PlayTennis

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

import pandas as pd
import numpy as np


In [4]:
from google.colab import files
uploaded = files.upload()


Saving PlayTennis.csv to PlayTennis (1).csv


NameError: ignored

In [6]:
import io
tennis_data = pd.read_csv(io.BytesIO(uploaded['PlayTennis.csv']))
tennis_data

Outlook Temperature Humidity    Wind PlayTennis
0      Sunny         Hot     High    Weak         No
1      Sunny         Hot     High  Strong         No
2   Overcast         Hot     High    Weak        Yes
3       Rain        Mild     High    Weak        Yes
4       Rain        Cool   Normal    Weak        Yes
5       Rain        Cool   Normal  Strong         No
6   Overcast        Cool   Normal  Strong        Yes
7      Sunny        Mild     High    Weak         No
8      Sunny        Cool   Normal    Weak        Yes
9       Rain        Mild   Normal    Weak        Yes
10     Sunny        Mild   Normal  Strong        Yes
11  Overcast        Mild     High  Strong        Yes
12  Overcast         Hot   Normal    Weak        Yes
13      Rain        Mild     High  Strong         No

In [7]:
# 데이터 전처리
tennis_data.Outlook = tennis_data.Outlook.replace('Sunny', 0)
tennis_data.Outlook = tennis_data.Outlook.replace('Overcast', 1) 
tennis_data.Outlook = tennis_data.Outlook.replace('Rain', 2)
tennis_data.Temperature = tennis_data.Temperature.replace('Hot', 3) 
tennis_data.Temperature = tennis_data.Temperature.replace('Mild', 4) 
tennis_data.Temperature = tennis_data.Temperature.replace('Cool', 5)
tennis_data.Humidity = tennis_data.Humidity.replace('High', 6) 
tennis_data.Humidity = tennis_data.Humidity.replace('Normal', 7)
tennis_data.Wind = tennis_data.Wind.replace('Weak', 8) 
tennis_data.Wind = tennis_data.Wind.replace('Strong', 9)
tennis_data.PlayTennis = tennis_data.PlayTennis.replace('No', 10) 
tennis_data.PlayTennis = tennis_data.PlayTennis.replace('Yes', 11)
tennis_data

Outlook  Temperature  Humidity  Wind  PlayTennis
0         0            3         6     8          10
1         0            3         6     9          10
2         1            3         6     8          11
3         2            4         6     8          11
4         2            5         7     8          11
5         2            5         7     9          10
6         1            5         7     9          11
7         0            4         6     8          10
8         0            5         7     8          11
9         2            4         7     8          11
10        0            4         7     9          11
11        1            4         6     9          11
12        1            3         7     8          11
13        2            4         6     9          10

In [8]:
# 속성(X)과 클래스(y) 분리

X = np.array(pd.DataFrame(tennis_data, columns = ['Outlook', 'Temperature', 'Humidity', 'Wind']))
y = np.array(pd.DataFrame(tennis_data, columns = ['PlayTennis']))

In [9]:
#훈련 데이터 및 테스트 데이터 약 7:3 분리

X_train, X_test, y_train, y_test = train_test_split(X, y)

In [10]:
print('X_train :', X_train) 
print('X_test :', X_test) 
print('y_train :', y_train) 
print('y_test :', y_test)

X_train : [[0 3 6 8]
 [0 3 6 9]
 [2 4 6 8]
 [2 5 7 9]
 [0 4 6 8]
 [0 5 7 8]
 [1 3 6 8]
 [1 3 7 8]
 [2 4 7 8]
 [2 5 7 8]]
X_test : [[2 4 6 9]
 [1 4 6 9]
 [0 4 7 9]
 [1 5 7 9]]
y_train : [[10]
 [10]
 [11]
 [10]
 [10]
 [11]
 [11]
 [11]
 [11]
 [11]]
y_test : [[10]
 [11]
 [11]
 [11]]


In [11]:
#gnb_clf 에 가우시안 나이브 베이즈 모델 저장
#gnb_clf 에 훈련 데이터 기반의 가우시안 나이브 베이즈 학습 모델 생성 후, 저장

gnb_clf = GaussianNB()
gnb_clf = gnb_clf.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
# 생성된 학습 모델에 테스트 데이터 입력
# 학습 모델을 통해 데스트 데이터 예측 결과 저장

gnb_prediction = gnb_clf.predict(X_test)

In [14]:
# 나이브 베이즈 분류 모델 성능 측정

from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report 
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [15]:
# 실제값과 예측값 간 confusion matrix
# 결과적으로 1 개 틀렸음. 위 [1 1]이 [2 0]이 되어야 함
print('Confusion Matrix') 
print(confusion_matrix(y_test, gnb_prediction))

Confusion Matrix
[[1 0]
 [3 0]]
